directories:
  output: .
  buildResources: build
appId: com.reeceyboin.popquiz
productName: PopQuiz
copyright: Copyright Â© 2025 Reece N
files:
  - filter:
      - electron/**/*
      - dist/**/*
      - dist-player/**/*
      - package.json
asar: true
win:
  target:
    - target: portable
      arch:
        - x64
  icon: build/icon.ico
  artifactName: PopQuiz.exe
electronVersion: 38.7.2
